apiVersion: scheduledscale.io/v1alpha1
kind: CronJobSuspend
metadata:
  name: suspend-me
spec:
  cronjob:
    matchLabels:
      suspend-me: "true"
  stateAt:
    # crontab: minute / hour / day / month / day week
    - at: "5,15,25,35,45,55 * * * * *"
      suspend: true

      annotations:
        add:
          "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

    - at: "10,20,30,40,50,0 * * * * *"
      suspend: false

      annotations:
        remove:
          - "cluster-autoscaler.kubernetes.io/safe-to-evict"
