apiVersion: scheduledscale.io/v1alpha1
kind: DeploymentScaling
metadata:
  name: scale-up
spec:
  onDelete:
    removePodDisruptionBudget: true # will only

  deployment:
    matchLabels:
      scale-me: "true"
  scaleTo:
    # crontab: minute / hour / day / month / day week
    - at: "10,25,40 * * * * *"
      replicas: 2

      podDisruptionBudget:
        enabled: true
        minAvailable: 1

      annotations:
        add:
          "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    - at: "15,30,45 * * * * *"
      replicas: 1

      podDisruptionBudget:
        enabled: false

      annotations:
        remove:
          - "cluster-autoscaler.kubernetes.io/safe-to-evict"
    - at: "20,35,50 * * * * *"
      replicas: 0
