apiVersion: scheduledscale.io/v1alpha1
kind: DeploymentScaling
metadata:
  name: scale-down
spec:
  deployment:
    matchLabels:
      scale-me: "true"
  scaleTo:
    - at: "20 * * * * *"
      replicas: 1

      podDisruptionBudget:
        enabled: false
      
      annotations:
        remove:
        - "cluster-autoscaler.kubernetes.io/safe-to-evict"


