apiVersion: scheduledscale.io/v1alpha1
kind: HorizontalPodAutoscalerScaling
metadata:
  name: hpa-me
spec:
  horizontalPodAutoscaler:
    matchLabels:
      hpa-me: "true"
  scaleTo:
    - at: "10,25,40,55 * * * * *"
      minReplicas: 1
      maxReplicas: 5

      annotations:
        remove:
          - "cluster-autoscaler.kubernetes.io/safe-to-evict"
    - at: "15,30,45,0 * * * * *"
      minReplicas: 1
      maxReplicas: 1

      annotations:
        add:
          "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    - at: "20,35,50 * * * * *"
      minReplicas: 2
      maxReplicas: 5


