image:
  registry: "ghcr.io"
  repository: "gijsvandulmen/scheduledscale"
  tag: "1.0"

  pullPolicy: Always

logLevel: "INFO"

resources:
  limits:
    memory: 500Mi
    cpu: 300m
  requests:
    memory: 50Mi
    cpu: 30m