apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cronjobsuspends.scheduledscale.io
spec:
  group: scheduledscale.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronjob:
                  type: object
                  properties:
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                stateAt:
                  type: array
                  items:
                    type: object
                    properties:
                      at:
                        type: string
                      suspend:
                        type: boolean
                      annotations:
                        type: object
                        properties:
                          add:
                            additionalProperties:
                              type: string
                            type: object
                          remove:
                            type: array
                            items:
                              type: string
            status:
              type: object
              properties:
                errorMessage:
                  type: string
  names:
    kind: CronJobSuspend
    plural: cronjobsuspends
  scope: Namespaced
