apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deploymentscalings.scheduledscale.io
spec:
  group: scheduledscale.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                onDelete:
                  type: object
                  properties:
                    removePodDisruptionBudget:
                      type: boolean
                deployment:
                  type: object
                  properties:
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                scaleTo:
                  type: array
                  items:
                    type: object
                    properties:
                      at:
                        type: string
                      replicas:
                        type: integer
                        minimum: 0
                      podDisruptionBudget:
                        type: object
                        oneOf:
                          - properties:
                            required: [ "minAvailable" ]
                          - properties:
                            required: [ "maxAvailable" ]
                        properties:
                          minAvailable:
                            type: integer
                            minimum: 1
                          maxAvailable:
                            type: integer
                            minimum: 1
                      annotations:
                        type: object
                        properties:
                          add:
                            additionalProperties:
                              type: string
                            type: object
                          remove:
                            type: array
                            items:
                              type: string

            status:
              type: object
              properties:
                errorMessage:
                  type: string
  names:
    kind: DeploymentScaling
    plural: deploymentscalings
  scope: Namespaced
