apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deploymentscalings.scheduledscale.io
spec:
  group: scheduledscale.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Labels
          type: string
          description: Labels to match on
          jsonPath: .spec.deployment.matchLabels
        - name: Registered
          type: boolean
          jsonPath: .status.registered
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["deployment", "scaleTo"]
              properties:
                onDelete:
                  type: object
                  properties:
                    removePodDisruptionBudget:
                      type: boolean
                deployment:
                  type: object
                  required: ["matchLabels"]
                  properties:
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                scaleTo:
                  x-kubernetes-validations:
                    - rule: "size(self) >=1"
                      message: "there should be at least one scaleTo"
                  type: array
                  items:
                    type: object
                    required: ["at", "replicas"]
                    properties:
                      at:
                        type: string
                      replicas:
                        type: integer
                        minimum: 0
                      podDisruptionBudget:
                        type: object
                        oneOf:
                          - properties:
                            required: [ "enabled" ]
                        properties:
                          enabled:
                            type: boolean
                          minAvailable:
                            type: integer
                            minimum: 1
                          maxUnavailable:
                            type: integer
                            minimum: 1
                      annotations:
                        type: object
                        properties:
                          add:
                            additionalProperties:
                              type: string
                            type: object
                          remove:
                            type: array
                            items:
                              type: string

            status:
              type: object
              properties:
                registered:
                  type: boolean
  names:
    kind: DeploymentScaling
    plural: deploymentscalings
  scope: Namespaced
