apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: horizontalpodautoscalerscalings.scheduledscale.io
spec:
  group: scheduledscale.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["horizontalPodAutoscaler", "scaleTo"]
              properties:
                onDelete:
                  type: object
                  properties:
                    removePodDisruptionBudget:
                      type: boolean
                horizontalPodAutoscaler:
                  type: object
                  required: ["matchLabels"]
                  properties:
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                scaleTo:
                  x-kubernetes-validations:
                    - rule: "size(self) >=1"
                      message: "there should be at least one scaleTo"
                  type: array
                  items:
                    type: object
                    required: ["at"]
                    properties:
                      at:
                        type: string
                      minReplicas:
                        type: integer
                        minimum: 0
                      maxReplicas:
                        type: integer
                        minimum: 0
                      podDisruptionBudget:
                        type: object
                        oneOf:
                          - properties:
                            required: [ "minAvailable" ]
                          - properties:
                            required: [ "maxUnavailable" ]
                        properties:
                          minAvailable:
                            type: integer
                            minimum: 1
                          maxUnavailable:
                            type: integer
                            minimum: 1
                      annotations:
                        type: object
                        properties:
                          add:
                            additionalProperties:
                              type: string
                            type: object
                          remove:
                            type: array
                            items:
                              type: string

            status:
              type: object
              properties:
                registered:
                  type: boolean
  names:
    kind: HorizontalPodAutoscalerScaling
    plural: horizontalpodautoscalerscalings
  scope: Namespaced
